Post.create!( 
  [
    {
      title: "テニスイベントを開催します①",
      place: "東京都",
      venue: "コナミテニスコート西葛西",
      address: "東京都江戸川区西葛西a-b-c",
      date: "2020-03-01",
      start_time: "09:00:00",
      end_time: "12:00:00",
      explanation: "閲覧頂きありがとうございます！この度平日仕事終わりにもテニス活動ができるコミュニティを作成したく、投稿させて頂きました！",
      cost: 1000,
      recruit: 2,
      ave_low: 2,
      ave_high: 8,
      com_low: 1,
      com_high: 9,
      age: 20,
      sex: "",
      dominant: "",
      user_id: 1,
      image:"https://d1f5hsy4d47upe.cloudfront.net/b2/b2515848e899f0af65d6216a9eee6850_w.jpg"
     } ,
    {
      title: "テニスイベントを開催します②",
      place: "東京都",
      venue: "渋谷区テニスコート",
      address: "東京都渋谷区a-b-c",
      date: "2020-05-01",
      start_time: "09:00:00",
      end_time: "12:00:00",
      explanation: "閲覧頂きありがとうございます！この度休日にテニス活動ができるコミュニティを作成したく、投稿させて頂きました！",
      cost: 2000,
      recruit: 3,
      ave_low: "",
      ave_high: "",
      com_low: 1,
      com_high: 9,
      age: 40,
      sex: "",
      dominant: "",
      user_id: 2,
      image:"https://d1f5hsy4d47upe.cloudfront.net/a0/a048ed7dabbbe4ed073e882f542f70fc_w.jpg"
    },
    {
      title: "テニスイベントを開催します③",
      place: "岐阜県",
      venue: "中津川公園テニスコート",
      address: "岐阜県中津川市駒場a-b-c",
      date: "2020-07-01",
      start_time: "09:00:00",
      end_time: "12:00:00",
      explanation: "閲覧頂きありがとうございます！この度テニス活動ができるコミュニティを作成したく、投稿させて頂きました！",
      cost: 1000,
      recruit: 4,
      ave_low: 5,
      ave_high: 8,
      com_low: "",
      com_high: "",
      age: 30,
      sex: "",
      dominant: "左利き",
      user_id: 3,
      image: "https://d1f5hsy4d47upe.cloudfront.net/f5/f5c61a9bfc8f5e4ae05b11e3fadd906d_w.jpg"
    }
  ]
)